jihwankim97/dev-sync

stock-snap-back/hello_express.js
stock-snap-back/package-lock.json
stock-snap-back/package.json

What does this PR do?
프로젝트의 초기 폴더 구조를 설정합니다.
node_modules, 로그 파일, 빌드 결과물 등과 같은 불필요한 파일을 제외하기 위해 .gitignore를 추가합니다.
Why is this PR needed?
프로젝트 개발을 시작하기 위한 기본 구조를 설정합니다.
Additional Information
호환성에 영향을 주는 변경 사항은 없습니다.

feat: 익스프레스 프로젝트 생성

---

back-end/.env.example
front-end/package-lock.json
front-end/package.json
front-end/src/App.tsx
front-end/src/components/body/Main.body.css
front-end/src/components/body/Main.body.tsx

- 
- 메인페이지 바디 레이아웃 간략하게 작성- 예: 로그인 기능 버그 수정, 사용자 인증 로직 개선 등
-  스크롤 애니메이션 추가
- 프론트 담당자 레이아웃 수정 필요

feat(main-body): 메인페이지 바디 레이아웃 간략하게 작성. 스크롤 애니메이션 추가.

---

front-end/src/components/EditResume.tsx
front-end/src/components/GitRepoList.tsx
front-end/src/components/UserPage.tsx

- 
- Git 데이터 가져오기와 이력서 생성 로직 분리 및 레포지토리 선택 기능 추가.
- "Git 정보 가져오기" 버튼 클릭 시 레포지토리 데이터를 가져온 뒤 리스트를 화면에 표시하도록 수정.
- 레포지토리 리스트에서 선택된 항목만 이력서로 생성할 수 있도록 기능 분리.
- GitRepoList 컴포넌트를 추가하여 레포지토리 선택 UI와 체크박스 상태 관리 구현.
- 선택된 레포지토리 데이터를 부모 컴포넌트로 전달하여 이력서 생성에 활용하도록 로직 추가.
- UI 스타일 및 사용자 경험을 개선하여 동작이 직관적으로 보이도록 업데이트.
- [ o] 문서를 업데이트했습니다.
-

feat: EditResume 업데이트, GitRepoList 추가, UserPage 수정 - 레포지토리 선택 기능 구현

---

back-end/src/resume/resumeGeneration.Service.ts

프롬프트에서 profileData의 데이터를 정확히 반영하도록 개선하고, 불필요한 예시를 제거했습니다.
- 
- api 호출 프롬프트를 수정하여 예시로 작성된 데이터가 포트폴리오 데이터에 반영되지 않도록 수정

feat: profileData 기반 프롬프트 개선

---

front-end/src/components/Header.tsx
front-end/src/components/contact/Contact.styles.ts
front-end/src/components/contact/Contact.tsx
front-end/src/components/contact/ContactForm.styles.ts
front-end/src/components/contact/ContactForm.tsx
front-end/src/main.tsx

-  프론트앤드 내 문의사항 리스트 출력 페이지 작성.
- 관리자에세 문의 하기 폼 페이지 작성.
- 서버 코드 필요

Feature/front contact layout  프론트앤드 내 문의사항 리스트 출력, 관리자에세 문의 하기 폼 작성.

---

back-end/env.exemple
back-end/package-lock.json
back-end/package.json
back-end/src/app.module.ts
back-end/src/contact/contact.controller.ts
back-end/src/contact/contact.module.ts
back-end/src/contact/contact.service.ts

- 문의사항을 관리자의 메일로 메일 쓰기를 해주는 contactService 백엔드 코드 작성
- contact 서비스, 컨트롤러, 모듈 추가

feat:문의사항을 관리자의 메일로 메일 쓰기를 해주는 contactService 백엔드 코드 작성

---

back-end/env.exemple
back-end/src/contact/contact.controller.ts
back-end/src/contact/contact.dto.ts
back-end/src/contact/contact.service.ts
front-end/src/components/contact/Contact.tsx

contact-dto 생성
문의사항 메일 보내기 컨트롤러 작성
기능 테스트 완료
데이터베이스 저장 필요
- 
- contact-dto 생성
- 문의사항 메일 보내기 컨트롤러 작성
- 프론트 연동 완료
- 기능 테스트 완료
- 데이터베이스 저장 필요
- [ o] 문서를 업데이트했습니다.
-

feat: contact 문의 기능 api 작성

---

back-end/src/user/user.dto.ts
back-end/src/user/user.entity.ts

- 
- user 테이블 전화번호, 생년월일 데이터 타입 변경
- updateUserDto 타입도 따라 변경
-

feat: user 테이블 전화번호, 생년월일 데이터 타입 변경, updateUserDto 타입도 따라 변경

---

back-end/src/posts/category.service.ts
back-end/src/posts/posts.module.ts

- 
- Category테이블& 서비스 정의
- 서버 실행시 카테고리 초기화
- [ O] 코드 리뷰를 완료했습니다.
- [ O] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.
- [ X] 문서를 업데이트했습니다.
-

feat: Category테이블& 서비스 정의, 서버 실행시 카테고리 초기화

---

back-end/src/posts/post.entity.ts
back-end/src/posts/posts.service.ts

- 
- 데이터베이스 카테고리, 계시글 테이블 조회 서비스 코드 추가
- 데이터베이스 카테고리, 계시글 테이블 추가&삭제 서비스 코드  추가
-

feat:postService 작성데이터베이스 카테고리, 계시글 조회 및 추가&삭제 서비스 알고리즘 작성

---

back-end/src/posts/dto/category/get-posts-by-category.dto.ts
back-end/src/posts/posts.controller.ts
back-end/src/posts/posts.service.ts

- 
- category 컨트롤러 추가
API:  
- 모든 카테고리 가져오기: getCateGories. --> Get('/categories')
- 특적 카테고리에 속한 게시글 가져오기: getPostsByCategory.  -->. Get('/categories/posts')
- category dot 작성
-

feat:카테고리 컨트롤러 작성 및, dto 작성

---

back-end/src/posts/dto/category/get-posts-by-category.dto.ts
back-end/src/posts/posts.controller.ts

- 
- category API URL및, Dto 개선
- 카테고리 이름으로 게시글 조회 API URL을 직관적으로 개선
- Dto를 통한 클라이언트 입력값을 소문자로 변환하고 공백을 제거하여 안정성을 높임
-

feat: category API URL및, Dto 개선

---

back-end/src/posts/dto/post/create-post.dto.ts
back-end/src/posts/dto/post/get-posts-by-user-id.dto.ts
back-end/src/posts/dto/post/update-post.dto.ts
back-end/src/posts/post.http
back-end/src/posts/posts.controller.ts
back-end/src/posts/posts.module.ts
back-end/src/posts/posts.service.ts
back-end/src/user/user.controller.ts

- 
-GET, posts/categories -> 모든 카테고리 조회
-GET, posts/ -> 모든 게시글 조회
-GET, posts/categories/:name -> 카테고리 이름으로 게시글 조회
-GET, posts/users/:email -> 유저 이메일로 게시글 조회
-GET, posts/top -> 조회수 상위 n개 게시글 조회
-POST, posts/ -> 게시글 생성
-DELETE, posts/:id -> 게시글 삭제
-PATCH, posts/:id -> 게시글 수정
-PATCH, posts/:id/view -> 게시글 조회수 증가
-

feat: post API 작성& 샘플 http요청 코드 작성

---

back-end/src/app.module.ts
back-end/src/posts/category.service.ts
back-end/src/posts/entities/category.entity.ts
back-end/src/posts/entities/command.entity.ts
back-end/src/posts/entities/like.entity.ts
back-end/src/posts/entities/post.entity.ts
back-end/src/posts/posts.module.ts
back-end/src/posts/posts.service.ts
back-end/src/user/user.entity.ts

- 
- like, comment 데이터베이스 테이블 추가
-

feat: like, comment 데이터베이스 테이블 추가

---

back-end/src/posts/category.service.ts
back-end/src/posts/dto/category/get-posts-by-category.dto.ts
back-end/src/posts/dto/post/create-post.dto.ts
back-end/src/posts/dto/post/update-post.dto.ts
back-end/src/posts/entities/category.entity.ts
back-end/src/posts/post.http
back-end/src/posts/posts.controller.ts
back-end/src/posts/posts.service.ts

- 
- 카테고리 테이블 name 속성명 category로 변경
- createPost api 호출 시 바디 user_id 삭제, 쿠키에서 user_id 가져오도록 변경
- updatePost api 호출 시 바디 user_id 삭제, 쿠키에서 user_id 가져오도록 변경
-

refactor: 카테고리 테이블 name 속성명 category로 변경

---

back-end/src/app.module.ts
back-end/src/posts/dto/comment/add-comment.dto.ts
back-end/src/posts/dto/comment/update-comment.dto.ts
back-end/src/posts/entities/comment.entity.ts
back-end/src/posts/post.http
back-end/src/posts/posts.controller.ts
back-end/src/posts/posts.module.ts
back-end/src/posts/posts.service.ts
back-end/src/user/user.service.ts

- 
- Post: posts/comment -> 댓글 생성
- Get: posts/comment/:post_id  -> 댓글 가져오기
- Patch: posts/comment -> 댓글 수정
- Delete: posts/comment/:id -> 댓글 삭제
-

Feature/post comment "feat: comment api 작성"

---

back-end/src/posts/posts.controller.ts

- 
- post controller 세션 인증 로직 수정
-

bug: POST API에서 세션 인증이 되지 않는 버그 수정

---

back-end/src/posts/post.http

- post api 테스트 코드 수정
- create Post 인자로 "post_id": 1 추가
- [ x] 코드 리뷰를 완료했습니다.
- [ o ] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.

etc: post api 테스트 코드 수정

---

back-end/src/posts/posts.controller.ts
back-end/src/posts/posts.service.ts

- 
- 파일 업로드시 리턴값으로 [원래 파일명:url] 객체 형식의 속성값이 잘못 리턴되는 버그 수정
-

bug:파일 업로드시 리턴값으로 [원래 파일명:url] 객체 형식의 속성값이 잘못 리턴되는 버그 수정

---

back-end/src/posts/posts.controller.ts

- 
- 카테고리 API의 비동기 처리 문제 해결
- get category API 비동기 처리
-

bugfix:카테고리 API의 비동기 처리 문제 해결

---

back-end/src/posts/posts.controller.ts
back-end/src/posts/posts.service.ts

- 
- getCommentCount 메서드 추가하여 전체 댓글 수 반환
- getComments API에서 totalCount도 함께 응답
- 프론트에서 페이지네이션 구현을 위한 개선
-

feat: 댓글 조회 api에  개수 조회 기능 추가

---

back-end/src/posts/posts.service.ts

- 댓글 API 응답에 user_name 추가 및, 응답 형식 수정
- 기존->데이터베이스  리턴,  현재-> 데이터베이스에서 데이터를 조회하여 정제 후 리턴.
- [ o] 문서를 업데이트했습니다.

refactor: 댓글 API 응답에 user_name 추가 및, 응답 형식 수정

---

back-end/src/posts/posts.service.ts

- 
-  댓글 API 응답에 user_id, profile_image 정보 추가
-

refactor: 댓글 API 응답에 user_id, profile_image 정보 추가

---

back-end/src/posts/posts.service.ts

- 
- 댓글 API에서 부모 댓글 ID 반환 추가
-

feat: 댓글 API에서 부모 댓글 ID 반환 추가

---

back-end/src/posts/entities/comment.entity.ts
back-end/src/posts/posts.service.ts

- 
- 댓글에서 post_id 컬럼 충돌 문제 해결
-

bugfix: 댓글에서 post_id 컬럼 충돌 문제 해결

---

front-end/package-lock.json
front-end/package.json
front-end/src/components/community/CommentGroup.tsx
front-end/src/components/community/CommentPost.tsx
front-end/src/components/community/CommentReply.tsx
front-end/src/components/community/CommunityComponent.tsx
front-end/src/components/community/ReadPost.tsx
front-end/src/components/community/WritePost.tsx
front-end/src/hooks/useGetCommentList.tsx
front-end/src/hooks/useSendComment.tsx
front-end/src/hooks/useToggleLike.tsx

- 
- 변경된 주요 내용을 간략히 작성합니다.
- 커뮤니티 댓글의 답글 기능 개발
- 답글 삭제 기능 
- 댓글 페이지 기능
- [o] 코드 리뷰를 완료했습니다.
- [o] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.
-

feat. 커뮤니티 대 댓글 기능 개발

---

back-end/src/posts/posts.service.ts

bugfix:게시글 삭제 시 타입 오류 해결

---

back-end/src/posts/posts.service.ts

- 
-전체 게시글 조회(getAllPosts) 시 유저 프로필 이미지(profile_image) 포함
-유저 ID로 게시글 조회(getPostsByUserId) 시 유저 프로필 이미지 포함
-카테고리로 게시글 조회(getPostsByCategory) 시 유저 정보 및 프로필 이미지 포함
-

feat:카테고리별 및 전체 게시글 조회 시 유저 프로필 이미지 포함

---

back-end/src/posts/posts.service.ts

- 
-게시글 조회(getAllPosts, getPostsByUserId, getPostsByCategory) 시 리턴값에 조회수 및 좋아요 갯수 추가
- 페이지네이션 기능 추가 예정

feat: 카테고리별 및 전체 게시글 조회 시 조회수 및 좋아요 데이터 포함

---

front-end/src/api/FetchCategories.tsx
front-end/src/api/GetCommentList.tsx
front-end/src/api/GetLikeCount.tsx
front-end/src/api/RemoveComment.tsx
front-end/src/api/RemovePost.tsx
front-end/src/api/SendComment.tsx
front-end/src/api/ToggleLike.tsx
front-end/src/components/community/CommentPost.tsx
front-end/src/components/community/CommentReply.tsx
front-end/src/components/community/CommunityComponent.tsx
front-end/src/components/community/CommunityLayout.tsx
front-end/src/components/community/DeletePostDialog.tsx
front-end/src/components/community/OptionBar.tsx
front-end/src/components/community/ReadPost.tsx
front-end/src/components/community/WritePost.tsx

- 
-  커뮤니티 게시물 페이지네이션 기능
- 커뮤니티 게시물 리스트 좋아요 및 댓글 갯수 표시 기능
- [o] 코드 리뷰를 완료했습니다.
- [o] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.
-

feat.커뮤니티 게시물 페이지네이션 기능 및 좋아요/댓글 표시 기능

---

back-end/src/posts/dto/post/update-post.dto.ts
back-end/src/posts/posts.service.ts

- 
- updatePost에서 post.user 접근 시 undefined 오류 수정.
-  postid로 포스트 정보를 가져오는 내부함수에서 유저정보를 릴레이션으로 반환하게끔 수정
-

bugfix: updatePost에서 post.user 접근 시 undefined 오류 수정

---

front-end/src/api/EditComment.ts
front-end/src/api/EditContentSave.ts
front-end/src/api/GetCommentList.tsx
front-end/src/api/RemovePost.tsx
front-end/src/components/community/CommentPost.tsx
front-end/src/components/community/CommunityComponent.tsx
front-end/src/components/community/DeletePostDialog.tsx
front-end/src/components/community/OptionBar.tsx
front-end/src/components/community/ReadPost.tsx
front-end/src/components/community/WritePost.tsx

- 
- 댓글 수정 레이아웃 및 기능 
-  게시물 작성시에 공통 이미지 업로드 시 화면에 나타나지 않는 에러 수정
- [O] 코드 리뷰를 완료했습니다.
- [O] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.Z
-

feat.댓글 수정 기능 및 수정시 레이아웃

---

front-end/src/components/Header.tsx
front-end/src/components/community/CommentPost.tsx
front-end/src/components/community/CommunityAction.tsx
front-end/src/components/community/CommunityComponent.tsx
front-end/src/components/community/CommunityLayout.tsx
front-end/src/components/community/OptionBar.tsx

-
- 홈페이지 헤더 모바일 반응형 레이아웃 추가
- 다크모드시 버튼의 배경이 어둡게 보이는 현상 수정
- 글쓰기, 댓글 버튼 클릭시 로그인창 띄우는 기능 추가
- [o] 코드 리뷰를 완료했습니다.
- [o] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.
-

feat. 헤더 모바일 반응형 레이아웃

---

front-end/src/components/GitPatchPage.tsx
front-end/src/components/MainCanvas.tsx
front-end/src/components/gitRepoList/GitRepoList.styles.ts
front-end/src/components/gitRepoList/GitRepoList.tsx

- 
- 이력서 git 연동 페이지 레이아웃 수정
- 이력서 페이지 모바일 ui 추가
- [O] 코드 리뷰를 완료했습니다.
- [O] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.

feat. 이력서 git 연동 페이지 레이아웃 수정/모바일 ui 추가

---

back-end/src/resume/dto/save-project-outcome.dto.ts
back-end/src/resume/dto/save-project.dto.ts
back-end/src/resume/dto/save-resume.dto.ts
back-end/src/resume/dto/save-skill.dto.ts
back-end/src/resume/entities/resume.entity.ts
back-end/src/resume/entities/skill.entity.ts
back-end/src/resume/resume.module.ts
back-end/src/resume/resume.service.ts

- 
- 이력서 소개(Introduction) 조회, 추가/수정, 삭제 기능 추가
- 이력서 스킬(str_skills, fam_skills) 저장 및 초기화 기능 추가
- 프로젝트/소개/스킬 관련 DTO 정의 및 적용
- Resume ↔ Skill 다대다 관계를 강점/익숙한 스킬로 분리
- Resume 엔티티에 title 필드 및 유효성 검사 추가
- [o] 코드 리뷰를 완료했습니다.
- [o] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.
-

feat: 이력서 introduction/skill/project 관리 기능 및 스킬 구조 개선

---

front-end/package-lock.json
front-end/package.json
front-end/src/components/resume/ResumeEditorPanel.tsx
front-end/src/components/resume/ResumeListExisting.tsx
front-end/src/components/resume/ResumePreviewPanel.tsx
front-end/src/page/resume/EditResumePage.tsx
front-end/src/page/resume/GitPatchPage.tsx
front-end/src/styles/resumeCommonStyle.ts

- 
-  기존 이력서 리스트 불러오기 클릭시 더미 데이터로 레이아웃 생성
- gitpatch 페이지의 하단 레이아웃 에러 수정
-

feat: 기존 이력서 리스트 더미 데이터로 레이아웃 구현

---

back-end/src/resume/resume.service.ts
front-end/package-lock.json
front-end/package.json
front-end/src/components/community/CommentPost.tsx
front-end/src/components/community/CommentReply.tsx
front-end/src/components/community/CommunityAction.tsx
front-end/src/components/community/CommunityLayout.tsx
front-end/src/components/community/DeletePostDialog.tsx
front-end/src/components/community/OptionBar.tsx
front-end/src/components/gitRepoList/GitRepoList.tsx
front-end/src/components/resume/CustomSection.tsx
front-end/src/components/resume/ResumeEditorPanel.tsx
front-end/src/components/resume/ResumeOptionBar.tsx
front-end/src/components/resume/ResumePreviewPanel.tsx
front-end/src/components/resume/SectionOrderManager.tsx
front-end/src/components/user/ProfileButton.tsx
front-end/src/layout/Header.tsx
front-end/src/layout/ResumeSetupLayout .tsx
front-end/src/layout/main.tsx
front-end/src/page/MainBodyPage.tsx
front-end/src/page/UserPage.tsx
front-end/src/page/community/CommunityListPage.tsx
front-end/src/page/community/ReadPostPage.tsx
front-end/src/page/community/WritePostPage.tsx
front-end/src/page/inquiry/InquiryPage.tsx
front-end/src/page/resume/EditResumePage.tsx
front-end/src/page/resume/GitConnectPage.tsx
front-end/src/page/resume/ResumeIntroPage.tsx
front-end/src/page/resume/ResumeListPage.tsx
front-end/vite.config.ts

-  빌드를 위한 불필요한 import 제거 및 정리
-  청크 사이즈 제한 수정 
-

chore:불필요 import 제거 및 빌드 청크 사이즈 제한 수정

---

back-end/src/resume/resumeGeneration.Service.ts

- 
- generateResume 결과값으로 생성된 resume 데이터가 반환되도록 변경
-

refactor : generateResume 결과값으로 생성된 resume 데이터가 반환되도록 변경

---

back-end/src/resume/dto/create-project.dto.ts
back-end/src/resume/dto/create-projects-width-outcomes.dto.ts
back-end/src/resume/dto/create-skill.dto.ts
back-end/src/resume/resume.service.ts
back-end/src/resume/resumeGeneration.Service.ts

-
- 변경된 주요 내용을 간략히 작성합니다.
- 리슘 프로젝트 생성 api dto  skill부분 id값 -> {id:number, name:string, icon:string}으로 변경
-

refactor: 리슘 프로젝트 생성 api dto 변경

---

back-end/src/resume/resume.controller.ts
back-end/src/resume/skill_seeder.service.ts

- 
- Devicon 아이콘 추출 시 plain, original 옵션을 모두 고려하도록 개선
- 기존에는 일부 아이콘 클래스가 잘못 생성되어 프론트에서 렌더링되지 않던 문제 수정
-

bugfix:Devicon 아이콘 클래스 추출 로직 수정 및 배치 처리 적용

---

back-end/src/resume/dto/create-introduction.dto.ts
back-end/src/resume/dto/create-profile.dto.ts
back-end/src/resume/dto/create-project-outcome.dto.ts
back-end/src/resume/dto/create-project.dto.ts
back-end/src/resume/dto/create-projects-width-outcomes.dto.ts
back-end/src/resume/dto/create-skills.dto.ts
back-end/src/resume/entities/profile.entity.ts
back-end/src/resume/enum/resume-type.enum.ts
back-end/src/resume/resume.controller.ts
back-end/src/resume/resume.service.ts
back-end/src/resume/resumeGeneration.Service.ts

- 
- saveBlock 메서드로 중앙화된 resume 블록 저장 시스템 구축
- DTO 속성 통일 (projects → items) 및 유효성 검사 개선
- 타입 기반 부분 저장 기능 구현
- 서비스 로직 최적화 및 에러 처리 개선
-

feat: resume 통합 블록 저장 시스템 구현 및 부분 저장 기능 완성

---

back-end/package-lock.json
back-end/package.json
front-end/src/components/resume/CreateSection.tsx
front-end/src/components/resume/ResumePreviewPanel.tsx
front-end/src/components/resume/sections/AchievementSection.tsx
front-end/src/components/resume/sections/CareerSection.tsx
front-end/src/components/resume/sections/ProfileSection.tsx
front-end/src/components/resume/sections/ProjectsSection.tsx
front-end/src/components/resume/sections/SkillsSection.tsx
front-end/src/hooks/useLocalSection.ts
front-end/src/page/resume/EditResumePage.tsx
front-end/src/page/resume/ResumeIntroPage.tsx
front-end/src/page/resume/ResumeListPage.tsx
front-end/src/redux/resumeSlice.ts
front-end/src/types/resume.type.ts

- 
-  api 데이터로 이력서 리스트 페이지 구현
-  이력서 데이터 개별 redux 저장 구현
-

feat: api데이터로 이력서 리스트 페이지 구현

---

back-end/src/main.ts
back-end/src/resume/resume.service.ts

- 
- removeResume에서 불필요한 사용자 검증 로직 제거
- getResume에서 author 정보 미반환으로 인한 버그 해결
- [o ] 코드 리뷰를 완료했습니다.
- [o ] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.
-

fix: 이력서 삭제 시 중복 사용자 검증 버그 수정

---

back-end/src/common/entity/base.entity.ts

-
- @VersionColumn() 추가
- createdAt, updatedAt, version 필드 클라이언트 노출 방지 @Exclude() 추가
- BaseModel과 BaseUuidModel 모두에 적용
- [o ] 코드 리뷰를 완료했습니다.
- [o ] 새로운 테스트를 추가하고, 기존 테스트가 통과함을 확인했습니다.
- [] 문서를 업데이트했습니다.
-

feat: BaseModel에 버전 관리 및 필드 제외 기능 추가

---

back-end/src/common/entity/base.entity.ts
back-end/src/main.ts

- BaseUuidModel에서 createdAt, updatedAt, version 필드 주석처리
- ClassSerializerInterceptor 설정으로 @Exclude() 기능 활용

refactor: BaseUuidModel 불필요한 필드 제거

---

back-end/src/resume/resumeGeneration.Service.ts

- 
- 이력서 생성 시 GitHub URL을 완전한 URL 형식으로 변환하여 링크 접근성 향상
-

feat: 이력서 생성 시 GitHub URL 형식 개선

---

front-end/src/components/community/CommentGroup.tsx
front-end/src/components/community/CommentPost.tsx
front-end/src/components/community/CommentReply.tsx
front-end/src/components/community/CommunityLayout.tsx
front-end/src/components/community/DeletePostDialog.tsx
front-end/src/components/community/OptionBar.tsx
front-end/src/components/resume/CreateSection.tsx
front-end/src/components/resume/ResumePreviewPanel.tsx
front-end/src/components/resume/sections/CareerSection.tsx
front-end/src/page/community/CommunityListPage.tsx
front-end/src/page/community/ReadPostPage.tsx
front-end/src/page/community/WritePostPage.tsx
front-end/src/page/resume/ResumeListPage.tsx

-
- 커뮤니티 post edit시 에러 fix
- 게시물 하위 댓글 입력시 에러 fix 
- 게시물 삭제 에러 fix
- 게시물 조회수 증가 에러 fix

resume type 변경으로 인한 커뮤니티 관련 버그 fix
